### ISSUE TITLE
Please check the results of my GBSS

### ISSUE THREAD

**Issue by thinkpad9955** [arash-n/GBSS#10]
[GM_skel_0.65.nii.gz](https://github.com/arash-n/GBSS/files/4901134/GM_skel_0.65.nii.gz)

[all_bin.nii.gz](https://github.com/arash-n/GBSS/files/4901137/all_bin.nii.gz)
[all_fIC_filled.nii.gz](https://github.com/arash-n/GBSS/files/4901139/all_fIC_filled.nii.gz)
[all_ODI_filled.nii.gz](https://github.com/arash-n/GBSS/files/4901140/all_ODI_filled.nii.gz)
[all_fIC_skeletonised.nii.gz](https://github.com/arash-n/GBSS/files/4901141/all_fIC_skeletonised.nii.gz)
[all_fIC_filled.nii.gz](https://github.com/arash-n/GBSS/files/4901144/all_fIC_filled.nii.gz)
[all_ODI_filled.nii.gz](https://github.com/arash-n/GBSS/files/4901147/all_ODI_filled.nii.gz)
[all_ODI_skeletonised.nii.gz](https://github.com/arash-n/GBSS/files/4901148/all_ODI_skeletonised.nii.gz)

**Comment by arash-n** [comment]
Overall these look OK and are acceptable. I had better looking skeletons with a threshold of 0.65. This may not matter that much. But, it may decrease your sensitivity to pickup small differences and diminish your significance, as TFCE uses connectivity to enhance significance of a cluster. I would run stats and if you were seeing a lot of small clusters this means that you probably need to change the GM thresholds to make more connected GM-skeleton mask.

-Arash

**Comment by thinkpad9955** [comment]
Thanks for your suggestion.
