### ISSUE TITLE
buildtemplateparallel.sh outdated

### ISSUE THREAD

**Issue by ezefarrher** [arash-n/GBSS#11]
Hi, I've just noticed that you use buildtemplateparallel.sh from ANTs to create the template. However, in ANTs they say that they'd rather recommend to use antsMultivariateTemplateConstruction2.sh instead of buildtemplateparallel.sh in general.
Do you think it would also work in the framework of your GBSS?
Thank you!

**Comment by arash-n** [comment]
Hi, 

GBSS uses an older version of ANTs and should work just as well with antsMultivariateTemplateConstruction2.sh. However, the options/flags are a bit different and need to be modified accordingly.  Make sure that the intermediate templates are saved for QC. Sometimes the template drifts partially out of the field of view. If that occurs, you can use -y 0.

Hope that helps.

-Arash

**Comment by ezefarrher** [comment]
Thanks!
