### ISSUE TITLE
threshold in gbss_2_skel.sh

### ISSUE THREAD

**Issue by ezefarrher** [arash-n/GBSS#12]
Hi Arash,
the threshold in gbss_2_skel.sh, line 139:
fslmaths all_fIC_skeletonised -mul mean_GM_skeleton_mask_general **-thr 0.65** -bin all_lesion_fIC

does it refer to the same threshold defined in thresh (line 54)? if I choose another threshold, do I need to also change the one in line 139?

Thanks!

**Comment by arash-n** [comment]
Hi!

This is another threshold. This is supposed to filter out voxels with high fIC (NDI) that have been misclassified as gray matter, etc.

-Arash

**Comment by arash-n** [comment]
I believe at some point there was an issue with options that I fixed it. As a sanity check, it would be helpful to make sure that the options that you give are passed successfully to the script by adding "echo thresh=$thresh; echo perc=$perc".
