### ISSUE TITLE
threshold for bin_mean

### ISSUE THREAD

**Issue by ezefarrher** [arash-n/GBSS#13]
Hi Arash,

I'd like to ask you what's the aim of the last line in gbss_3_fill.sh (fslmaths bin_mean.nii.gz -thr 0.995 mask). The reason is that I'm getting a nice skeleton in bin_mean.nii.gz but it gets very much disconnected when the threshold 0.995 is applied. Is it possible to lower that threshold to e.g. 0.95?

Thank you!

**Comment by arash-n** [comment]
Hi,

I wouldn't change that. As this basically ensures no zero voxel enters voxelwise statistics. You can however do the following:

1) Decrease the thresholds in these lines:

fslmaths fIC_non_lesion_bin_s_2 -thr 0.05 -bin -mul all_lesion.nii.gz -mul fIC_filler -add fIC_non_lesion all_fIC_filled
fslmaths ODI_non_lesion_bin_s_2 -thr 0.05 -bin -mul all_lesion.nii.gz -mul ODI_filler -add ODI_non_lesion all_ODI_filled

from 0.05 to something smaller (e.g., 0.025)

2) Increase smoothing. Wherever you see -s 2, you can do -s 3.

Best,

Arash

**Comment by ezefarrher** [comment]
Hi Arash,

thank you for the answer.  I will try that.

Best
