### ISSUE TITLE
GBSS-DKI?

### ISSUE THREAD

**Issue by alzbetaSM** [arash-n/GBSS#14]
Dear Arash, 

we think, this would be great complement to the TBSS analysis on our data. However, I have a few questions an would like to kindly ask you for your advices. 

First, I have more general question. With our dataset we aim to the DKI analysis. Is that possible to use your scripts for "GBSS-DKI" just by changing ODI and fIC parameters for DKI ones? Or do you see any reason, why this would fail? 

If it would be OK, then I would have a question about the buildtemplateparallel.sh function (ANTs) in gbss_reg_1 script. In this issues forum someone wrote the function is outdated. You suggested to use the antsMultivariateTemplateConstruction2.sh with adjusted flags. I am not realy familiar with ANTs and differences between these two functions, could you please be more specific about changes needed? 

Thank you for your advices. 
Alzbeta

**Comment by arash-n** [comment]
Hi Alzbeta,

The script needs to make (i) gray matter probability and (ii) pseudo T1 maps in the diffusion space. The original implementation provided here, FA maps are used to estimate white matter probability (fWM) and Free water map (from NODDI) as an estimate for CSF probability maps (fCSF). The gray matter is then calculated by subtracting these two from 1. If you provide free water maps and FA maps. Then the script should work with any parameter map (from DKI or any other modeling) with some minor tweaks to the script. 

Alternatively, I have experimented with multi-shell multi-tissue spherical deconvolution that provides tissue probability maps using multi-shell DWI:

https://mrtrix.readthedocs.io/en/latest/constrained_spherical_deconvolution/multi_shell_multi_tissue_csd.html

For ANTs, if you already have the older version running with buildtemplateparallel.sh, I think it should just work just fine for GBSS. But, if you have the newer versions installed, you need to edit the script to use antsMultivariateTemplateConstruction2.sh.

Best,

Arash
