### ISSUE TITLE
NODDI AMICO

### ISSUE THREAD

**Issue by ezefarrher** [arash-n/GBSS#15]
Hi Arash,

do you know if it would make a difference to use NODDI AMICO instead of using  the NODDI matlab package in GBSS?

Best

**Comment by arash-n** [comment]
Hi,

It should not in theory. I have not tested AMICO, myself. But, others have used it in their work with GBSS:

https://academic.oup.com/cercor/article/30/5/2948/5675110?login=true

https://www.frontiersin.org/articles/10.3389/fonc.2021.641359/full

Best,

Arash

**Comment by ezefarrher** [comment]
Hi, ok. Thank you.
Best
