### ISSUE TITLE
input threshold in gbss_2_skel.sh

### ISSUE THREAD

**Issue by ezefarrher** [arash-n/GBSS#16]
Hi Arash,

do you think it would be meaningful to use an input threshold e.g. 0.45 in gbss_2_skel.sh? The reason for using such a low value, is because otherwise the skeleton I get is very disconnected. In addition to that, I'm also using -thr 0.025 (instead of 0.05) in the following lines.

fslmaths fIC_non_lesion_bin_s_2 -thr 0.025 -bin -mul all_lesion.nii.gz -mul fIC_filler -add fIC_non_lesion all_fIC_filled
fslmaths ODI_non_lesion_bin_s_2 -thr 0.025 -bin -mul all_lesion.nii.gz -mul ODI_filler -add ODI_non_lesion all_ODI_filled

and increased -s 2 to -s 3

Would you please, have a look at the attached skeleton? I guess the reason I have troubles to get a good skeleton is the large voxel size (2.5 mm iso).

[mask_thr045.nii.gz](https://github.com/arash-n/GBSS/files/7443312/mask_thr045.nii.gz)

Thank you very much in advance.

**Comment by arash-n** [comment]
Hi,

As you said, I also think image resolution is key (your voxel size is twice as large as what I used 2 mm iso). 

For the filling part (gbss_3), I think changing parameters as you did makes perfect sense. I think 0.45 as your threshold is a bit low. You are more tolerant to partial volume effect from CSF than the underlying white matter, as NODDI corrects for free water as it fits the model. 

You can change the thresholding to reflect that with a two level thresholding approach: 1) global threshold (e.g., > 0.5); 2) followed by a threshold for white matter pve. This is already implemented in the gbss_2 script:

fslmaths all_WM_skeletonised -mul mean_GM_skeleton_mask_general -thr 0.3 -bin all_lesion_WM

I think you can lower your threshold to say 0.5. You can also change 0.3 to 0.35 (i.e., tolerating up to 35 percent white matter). Also, before doing stats I would get rid of small clusters (using cluster function):

[mask.nii.gz](https://github.com/arash-n/GBSS/files/7444248/mask.nii.gz)

Best,

Arash

**Comment by ezefarrher** [comment]
Hi Arash,

thank you for the answer. 
So, I did now use an input thr of 0.5 and changed the WM pve to 0.35.
In addition to that, I removed clusters with less than 10 voxels. Unfortunately the mask I get is still quite disconnected in my opinion:
[mask_clean.nii.gz](https://github.com/arash-n/GBSS/files/7453947/mask_clean.nii.gz)

Is there any other tweak you would do in order to improve the mask? Otherwise, would you go ahead with such a mask?

Thank you very much.

Kind regards

**Comment by arash-n** [comment]
I think a few things you should take into account:

1. The partial volumes are composite numbers and not absolute numbers. You just want the gray matter partial volume as  high as possible that enables you to do voxel-wise statistics. The thresholds we are using will be somewhat arbitrary. 

2. Even with higher resolution some parts of the brain are thin and you may not end up in the final mask. I think you can always provide the caveat of what parts of the GM were not included in the final mask.

3.  The most important factor for validity of voxel-wise analysis is to ensure that the final mask has enough connectivity.

4. Lastly, we are using the non-maximum-suppression perpendicular to the local tract structure algorithm from TBSS. This algorithm has not been optimized for GBSS and can definitely be tweaked for better skeletonization of GM.

**Comment by ezefarrher** [comment]
Hi, ok, thank you again for the answers.

Best
