### ISSUE TITLE
gbss_2_skel.sh error

### ISSUE THREAD

**Issue by abrarfaiyaz** [arash-n/GBSS#18]
```
Image Exception : #63 :: No image files match: /noddi_gbss/input/*GM*
terminate called after throwing an instance of 'armawrap::AWException'
  what():  No image files match: /noddi_gbss/input/*GM*
/noddi_gbss/GBSS/NODDI/gbss_2_skel.sh: line 110: 14432 Aborted                 (core dumped) fslmerge -t all_GM ${tmp_folder}/*GM*

```

I was wondering if the GM fraction maps should auto generate or we need to manually provide it?

**Comment by arash-n** [comment]
Hi!

It looks like the GM files were not created. They should have been created with gbss_1_reg.sh

The scripts are also sensitive to the location you are running them. Are the files in the /noddi_gbss/input directory?

-Arash

**Comment by abrarfaiyaz** [comment]
Yes they are, it looks like I'm running into error because of buildtemplateparallel.sh script which is not recommended in the v2.3.1 of ANTs. Can you suggest equivalent code for antsMultivariateTemplateConstruction.sh?

**Comment by arash-n** [comment]
I have not explicitly tested antsMultivariateTemplateConstruction2.sh for GBSS. But, I would use
antsMultivariateTemplateConstruction2.sh -d 3 -i 4 -f 6x4x2x1 -s 4x2x1x0vox -q 50x100x70x10 -n 0 -t SyN -m CC -y 0  -b 1 -z A_T1_weighted_brain_TEMPLATE 

Depending on the number of subjects you are analyzing and the computing you have access to, you can change -f, -s, and -q options.

-Arash

**Comment by abrarfaiyaz** [comment]
Thanks! Also, I find antsMultivariateTemplateConstruction.sh script has identical input params as buildtemplateparallel.sh. I can try this as well, right? Or there's any other catch?

**Comment by arash-n** [comment]
It should be OK as far as I know.
