### ISSUE TITLE
fsl_sub -r flag

### ISSUE THREAD

**Issue by anbai106** [arash-n/GBSS#5]
Hellow:
Thank for your work, I have a question when you create the template by using fsl_sub, you have a -r falg to point to the reference image(template), but I checked out the fsl fsl_sub wiki, there is no this flag, in my linux and mac, there are not neither, my fsl_sub versin is V1.1, can you please let me konw your fsl_sub version????

Thanks in advance

Hao

**Comment by arash-n** [comment]
Hey Hao,

fsl_sub treats everything in front of it as a command in quotes. Therefore, -r refers to reference image for antsApplyTransforms command and does not have anything to do with the fsl_sub command.

Best,

Arash
