### ISSUE TITLE
Not clear for the tutorial 

### ISSUE THREAD

**Issue by anbai106** [arash-n/GBSS#6]
Hi, after reading your original paper, and I tried to try your pipeline, but I found that the tutorial in the github is not so clear,  I created the required output structure for the NODDI maps, and run the first command which is Ok, and then cd output_directory, and run the second script : gbss_2_skel.sh ., which gave me errors, do you have a better explanation for this different steps, because I found it very hard to understand.

Thanks in advance

Hao

**Comment by arash-n** [comment]
Hey Hao,

There have been a few people who had no problem using it. But, it would be great if you could give us feedback so that we can make our mini-tutorial clearer. 

For your own errors, please send me a log of your errors so that I can help you debug the script.

Cheers,

Arash
