### ISSUE TITLE
wrong_registration

### ISSUE THREAD

**Issue by Hui2019-creat** [arash-n/GBSS#7]
Hi Arash,
when we run the step of buildtemplateparallel.sh, we found that D1_template created could not match with the MNI_template, are there any parameters should I adjust?
looking forward to your reply
Yours 
Hui Hong

**Comment by arash-n** [comment]
Hi Hui,

That is the way buildtemplateparallel.sh creates template and it would not remain in the MNI space (and also newer versions of the script: antsMultivariateTemplateConstruction2.sh script). The only thing that stays the same is the image dimensions. 

What I used to do was to use the new template space for my post processing/voxel-wise statistics. Once I have my results in the new template space, I would use flirt/fnirt (or other tools) to bring the results to the MNI space for final reporting to get MNI coordinates for reporting.

Hope this helps.

-Arash

**Comment by Hui2019-creat** [comment]
Thank you very much! I'll try the way you suggest.
