### ISSUE TITLE
the Atropos command missing

### ISSUE THREAD

**Issue by thinkpad9955** [arash-n/GBSS#8]
Dear sirs,
  Thanks for your GBSS code, Now I meet a problem about two commands missing Atropos -d 3 -a. gbss_1_reg.sh  (line 166: can not find command Atropos).And gbss_1_reg.sh (line 204 ImageMath command)  missing.

FSL version5.0.
ANTs version is the latest.

Thanks for your help.

**Comment by arash-n** [comment]
Hi,

What happens if you type Atropos and ImageMath in the terminal?

-Arash

**Comment by thinkpad9955** [comment]
Done, They are all parts of ANTs, Thanks!
