### ISSUE TITLE
D1-template.nii.gz does not exist

### ISSUE THREAD

**Issue by thinkpad9955** [arash-n/GBSS#9]
+ mkdir /root/test/FA/D1
+ cp /root/test/FA/FA/Sub001_pseudoT1.nii.gz /root/test/FA/D1/
+ cd /root/test/FA/D1
+ '[' 1 == 1 ']'
+ echo 'OPTION 1: Creating Template Image'
OPTION 1: Creating Template Image
+ buildtemplateparallel.sh -d 3 -j 1 -o D1_ -n 0 -s MI -i 4 -m 30x50x20 -t GR -z /usr/share/fsl/5.0/data/standard/MNI152_T1_1mm.nii.gz Sub001_pseudoT1.nii.gz
do you have qsub? if not, then choose another c option ... if so, then check where the qsub alias points ...
+ '[' 1 == 0 ']'
+ cd /root/test/FA/FA
+ D1_folder=FA/D1
+ ref=/root/test/FA/D1/D1_template.nii.gz
+ for FAs in *_FA.nii.gz
++ echo Sub001_FA.nii.gz
++ cut -f1 -d_
+ a=Sub001
+ fsl_sub antsApplyTransforms -i Sub001_GM_frac.nii.gz -d 3 -e 0 -n NearestNeighbor -r /root/test/FA/D1/D1_template.nii.gz -t '/root/test/FA/D1/*Sub001_pseudoT1Warp.nii.gz' -t '/root/test/FA/D1/*Sub001_pseudoT1Affine.txt' -o /root/test/tmpspace/Sub001_GM.nii.gz --float
 file /root/test/FA/D1/D1_template.nii.gz does not exist . 

Hi,
Trouble you again, from the debug info,  The D1 folder is created automatically.
Where is D1_template.nii.gz ?

Best regards,
wang

**Comment by arash-n** [comment]
Hi Wang,

It looks like buildtemplateparallel.sh script is not working. I would check if the script is working on its own. Newer versions of ANTs may only have different script: antsMultivariateTemplateConstruction2.sh

If your ANTs version does only comes with antsMultivariateTemplateConstruction2.sh, gbss_1_reg.sh should be edited accordingly.

-Arash

**Comment by thinkpad9955** [comment]
echo 'Getting the Largest Component for WM fraction'
Getting the Largest Component for WM fraction
+ ImageMath 3 Sub001_WM_l_component.nii.gz GetLargestComponent Sub001_WM_frac.nii.gz
+ fslmaths Sub001_WM_frac.nii.gz -bin -sub Sub001_WM_l_component.nii.gz -thr 0 -bin Sub001_rim
+ fslmaths Sub001_WM_frac -mul Sub001_WM_l_component.nii.gz -mul 2 Sub001_WM_con
+ fslmaths Sub001_GM_frac -thr 0 -mul 1 Sub001_GM_con
+ fslmaths Sub001_GM_con -add Sub001_WM_con Sub001_pseudoT1
+ mkdir /root/test/FA/D1
+ cp /root/test/FA/FA/Sub001_pseudoT1.nii.gz /root/test/FA/D1/
+ cd /root/test/FA/D1
+ '[' 1 == 1 ']'
+ echo 'OPTION 1: Creating Template Image'
OPTION 1: Creating Template Image
+ buildtemplateparallel.sh -d 3 -j 1 -o D1_ -n 0 -s MI -i 4 -m 30x50x20 -t GR -z /usr/share/fsl/5.0/data/standard/MNI152_T1_1mm.nii.gz Sub001_pseudoT1.nii.gz
do you have qsub? if not, then choose another c option ... if so, then check where the qsub alias points ...
+ '[' : == 0 ']'
+ cd /root/test/FA/FA
+ D1_folder=FA/D1
+ ref=/root/test/FA/D1/D1_template.nii.gz
+ for FAs in *_FA.nii.gz
++ echo Sub001_FA.nii.gz
++ cut -f1 -d_
+ a=Sub001
+ fsl_sub antsApplyTransforms -i Sub001_GM_frac.nii.gz -d 3 -e 0 -n NearestNeighbor -r /root/test/FA/D1/D1_template.nii.gz -t '/root/test/FA/D1/*Sub001_pseudoT1Warp.nii.gz' -t '/root/test/FA/D1/*Sub001_pseudoT1Affine.txt' -o /root/test/tmpspace/Sub001_GM.nii.gz --float
 file /root/test/FA/D1/D1_template.nii.gz does not exist . 

I think the buildtemplateparallel.sh works. 
 do you have qsub?I do not know the meaning of qsub......

Best regards,
wang
